// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectRoot(arg1) {
  return window['go']['main']['App']['AddProjectRoot'](arg1);
}

export function CheckServiceHealth(arg1) {
  return window['go']['main']['App']['CheckServiceHealth'](arg1);
}

export function CheckSudoAccess() {
  return window['go']['main']['App']['CheckSudoAccess']();
}

export function GenerateProjectSSL(arg1) {
  return window['go']['main']['App']['GenerateProjectSSL'](arg1);
}

export function GetActiveServiceVersion(arg1) {
  return window['go']['main']['App']['GetActiveServiceVersion'](arg1);
}

export function GetAllRuntimeServices() {
  return window['go']['main']['App']['GetAllRuntimeServices']();
}

export function GetAllServicesStatus() {
  return window['go']['main']['App']['GetAllServicesStatus']();
}

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function GetProjectRoots() {
  return window['go']['main']['App']['GetProjectRoots']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetServiceStatus(arg1) {
  return window['go']['main']['App']['GetServiceStatus'](arg1);
}

export function GetServiceVersions(arg1) {
  return window['go']['main']['App']['GetServiceVersions'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRootCATrusted() {
  return window['go']['main']['App']['IsRootCATrusted']();
}

export function OpenContextTerminal(arg1) {
  return window['go']['main']['App']['OpenContextTerminal'](arg1);
}

export function OpenProjectInBrowser(arg1) {
  return window['go']['main']['App']['OpenProjectInBrowser'](arg1);
}

export function OpenProjectInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenProjectInEditor'](arg1, arg2);
}

export function RemoveProjectRoot(arg1) {
  return window['go']['main']['App']['RemoveProjectRoot'](arg1);
}

export function ScanProjects() {
  return window['go']['main']['App']['ScanProjects']();
}

export function SetServiceVersion(arg1, arg2) {
  return window['go']['main']['App']['SetServiceVersion'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function SyncHostsDomains() {
  return window['go']['main']['App']['SyncHostsDomains']();
}

export function ToggleProjectVHost(arg1, arg2) {
  return window['go']['main']['App']['ToggleProjectVHost'](arg1, arg2);
}

export function ToggleService(arg1, arg2) {
  return window['go']['main']['App']['ToggleService'](arg1, arg2);
}

export function TrustRootCA() {
  return window['go']['main']['App']['TrustRootCA']();
}
