// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CheckServiceHealth(arg1:string):Promise<service.LogMessage>;

export function CheckSudoAccess():Promise<boolean>;

export function GetActiveServiceVersion(arg1:string):Promise<string>;

export function GetAllRuntimeServices():Promise<Array<service.RuntimeServiceInfo>>;

export function GetAllServicesStatus():Promise<Array<service.Status>>;

export function GetAvailableServices():Promise<Array<service.Config>>;

export function GetBinarySourceInfo():Promise<Record<string, any>>;

export function GetServiceStatus(arg1:string):Promise<service.Status>;

export function GetServiceVersions(arg1:string):Promise<Array<string>>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function OpenContextTerminal(arg1:string):Promise<service.LogMessage>;

export function SetServiceVersion(arg1:string,arg2:string):Promise<service.LogMessage>;

export function StartService(arg1:string):Promise<service.LogMessage>;

export function StopService(arg1:string):Promise<service.LogMessage>;

export function ToggleService(arg1:string,arg2:boolean):Promise<service.LogMessage>;

export function GetProjects():Promise<Array<any>>;

export function ScanProjects():Promise<Array<any>>;

export function GetProjectRoots():Promise<Array<string>>;

export function AddProjectRoot(arg1:string):Promise<service.LogMessage>;

export function RemoveProjectRoot(arg1:string):Promise<service.LogMessage>;

export function ToggleProjectVHost(arg1:string,arg2:boolean):Promise<service.LogMessage>;

export function GenerateProjectSSL(arg1:string):Promise<service.LogMessage>;

export function OpenProjectInEditor(arg1:string,arg2:string):Promise<service.LogMessage>;

export function OpenProjectInBrowser(arg1:string):Promise<service.LogMessage>;

export function TrustRootCA():Promise<service.LogMessage>;

export function IsRootCATrusted():Promise<boolean>;

export function SyncHostsDomains():Promise<service.LogMessage>;
