// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSudoAccess() {
  return window['go']['main']['App']['CheckSudoAccess']();
}

export function GetAllServicesStatus() {
  return window['go']['main']['App']['GetAllServicesStatus']();
}

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function GetBinarySourceInfo() {
  return window['go']['main']['App']['GetBinarySourceInfo']();
}

export function GetServiceStatus(arg1) {
  return window['go']['main']['App']['GetServiceStatus'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function ToggleService(arg1, arg2) {
  return window['go']['main']['App']['ToggleService'](arg1, arg2);
}
