// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckSudoAccess():Promise<boolean>;

export function GetAvailableServices():Promise<Array<main.ServiceConfig>>;

export function GetServiceStatus(arg1:string):Promise<main.ServiceStatus>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function StartService(arg1:string):Promise<main.LogMessage>;

export function StopService(arg1:string):Promise<main.LogMessage>;

export function ToggleService(arg1:string,arg2:boolean):Promise<main.LogMessage>;
