// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CheckSudoAccess():Promise<boolean>;

export function GetActiveServiceVersion(arg1:string):Promise<string>;

export function GetAllServicesStatus():Promise<Array<service.Status>>;

export function GetAvailableServices():Promise<Array<service.Config>>;

export function GetBinarySourceInfo():Promise<Record<string, any>>;

export function GetServiceStatus(arg1:string):Promise<service.Status>;

export function GetServiceVersions(arg1:string):Promise<Array<string>>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function OpenContextTerminal(arg1:string):Promise<service.LogMessage>;

export function SetServiceVersion(arg1:string,arg2:string):Promise<service.LogMessage>;

export function StartService(arg1:string):Promise<service.LogMessage>;

export function StopService(arg1:string):Promise<service.LogMessage>;

export function ToggleService(arg1:string,arg2:boolean):Promise<service.LogMessage>;
